// front/src/App.svelte
<script>
import {Router, Route } from 'svelte-routing';
import Home from './Views/HomeView/HomeView.svelte';
import Register from './Views/RegisterView/RegisterView.svelte';
import Login from './Views/LoginView/LoginView.svelte';
import NotFound from './Views/404NotFoundView/404NotFoundView.svelte';


let url = window.location.pathname;
</script>

<Router {url}>
    <Route component={NotFound} />
    <Route path="/" component={Home} />
    <Route path="/register" component={Register} />
    <Route path="/login" component={Login} />
</Router>

// Front/src/App.jsx
import React from "react";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import Home from "./Components/Home/Home";
import NotFound from "./Components/NotFound/NotFound";
import Login from "./Components/Login/Login";
import Register from "./Components/Register/Register";
import Test from "./Components/test/test";

const App = () => {
  return (
    <div>
      <Router>
        <Routes>
          <Route path="/test" element={<Test />} />
          <Route path="/" element={<Home />} />
          <Route path="/login" element={<Login />} />
          <Route path="/register" element={<Register />} />
          <Route path="*" element={<NotFound />} />
        </Routes>
      </Router>
    </div>
  );
};

export default App;
